# -*- coding: utf-8 -*-
"""Python practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yGKmXnCOWTzoBy3r3nNL1D9TXvu24CQr
"""



"""TITANIC-PROJECT

Check out the Kaggle Titanic Challenge at the following link:

https://www.kaggle.com/c/titanic-gettingStarted

Note: You'll need to make an account to access the data.

Download the train.csv file and save it to the same location as your iPython Notebooks.
"""

# Commented out IPython magic to ensure Python compatibility.
#for data
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

#for visualization
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
# %matplotlib inline

from __future__ import division

# Use to grab data from the web(HTTP capabilities)
import requests

# We'll also use StringIO to work with the csv file, the DataFrame will require a .read() method
from io import StringIO

# Set up the Titanic csv file as a DataFrame
titanic_df = pd.read_csv('/content/train.csv')

# Let's see a preview of the data
titanic_df.head()

# We could also get overall info for the dataset
titanic_df.info()

"""All good data analysis projects begin with trying to answer questions. Now that we know what column category data we have let's think of some questions or insights we would like to obtain from the data. So here's a list of questions we'll try to answer using our new data analysis skills!

First some basic questions:

1.) Who were the passengers on the Titanic? (Ages,Gender,Class,..etc)
2.) What deck were the passengers on and how does that relate to their class?
3.) Where did the passengers come from?
4.) Who was alone and who was with family?
Then we'll dig deeper, with a broader question:

5.) What factors helped someone survive the sinking?
So let's start with the first question: Who were the passengers on the titanic?
"""

# Let's first check gender
sns.catplot(data=titanic_df, x='Sex', kind='count')

# Now let's seperate the genders by classes, remember we can use the 'hue' arguement here!
sns.catplot(data=titanic_df, x='Pclass', hue='Sex', kind='count')

"""Wow, quite a few more males in the 3rd class than females, an interesting find. However, it might be useful to know the split between males,females,and children. How can we go about this?"""

# We'll treat anyone as under 16 as a child, and then use the apply technique with a function to create a new column


# First let's make a function to sort through the sex

def male_female_child(passenger):
  #take the age and sex
  age,sex = passenger
  #compare the age, otherwise leave the sex
  if age < 16:
    return 'Child'
  else:
    return sex


# We'll define a new column called 'person', remember to specify axis=1 for columns and not index

titanic_df['Person'] = titanic_df[['Age','Sex']].apply(male_female_child,axis=1)

# Let's see if this worked, check out the first ten rows
titanic_df[0:10]

# Let's try the factorplot again!
sns.catplot(data=titanic_df, x='Pclass', hue='Person', kind='count')

"""Interesting, quite a bit of children in 3rd class and not so many in 1st! How about we create a distribution of the ages to get a more precise picture of the who the passengers were."""

# Quick way to create a histogram using pandas
titanic_df['Age'].hist(bins=70)

# We could also get a quick overall comparison of male,female,child
titanic_df['Person'].value_counts()

# Another way to visualize the data is to use FacetGrid to plot multiple kedplots on one plot

# Set the figure equal to a facetgrid with the pandas dataframe as its data source, set the hue, and change the aspect ratio.
fig = sns.FacetGrid(titanic_df, hue='Sex', aspect=4)

# Next use map to plot all the possible kdeplots for the 'Age' column by the hue choice
fig.map(sns.kdeplot,'Age', shade=True)

# Set the x max limit by the oldest passenger
oldest = titanic_df['Age'].max()

#Since we know no one can be negative years old set the x lower limit at 0
fig.set(xlim=(0, oldest))

#Finally add a legend
fig.add_legend()

# We could have done the same thing for the 'person' column to include children:

fig = sns.FacetGrid(titanic_df, hue='Person', aspect=4 )
fig.map(sns.kdeplot,'Age', shade=True)
oldest = titanic_df['Age'].max()
fig.set(xlim=(0, oldest))
fig.add_legend()

# Let's do the same for class by changing the hue argument:
fig = sns.FacetGrid(titanic_df, hue='Pclass', aspect=4)
fig.map(sns.kdeplot,'Age', shade=True)
oldest = titanic_df['Age'].max()
fig.set(xlim=(0, oldest))
fig.add_legend()

# Let's get a quick look at our dataset again
titanic_df.head()

"""So we can see that the Cabin column has information on the deck, but it has several NaN values, so we'll have to drop them."""

# First we'll drop the NaN values and create a new object, deck
deck = titanic_df['Cabin'].dropna()

# Quick preview of the decks
deck.head()

"""Notice we only need the first letter of the deck to classify its level (e.g. A,B,C,D,E,F,G)"""

# So let's grab that letter for the deck level with a simple for loop

#set an empty set:
levels = []

#for loop to grab first letter:
for level in deck:
  levels.append(level[0])

# Reset DataFrame and use factor plot
cabin_df = DataFrame(levels)
cabin_df.columns = ['Cabin']
sns.catplot(data=cabin_df, x='Cabin', palette='winter_d', kind='count')

"""Interesting to note we have a 'T' deck value there which doesn't make sense, we can drop it out with the following code:"""

# Redefine cabin_df as everything but where the row was equal to 'T'

cabin_df = cabin_df[cabin_df.Cabin != 'T']
#Replot
sns.catplot(data=cabin_df, x='Cabin', palette='summer', kind='count')

"""Great now that we've analyzed the distribution by decks, let's go ahead and answer our third question:

3.) Where did the passengers come from?
"""

# Let's take another look at our original data
titanic_df.head()

"""Note here that the Embarked column has C,Q,and S values. Reading about the project on Kaggle you'll note that these stand for Cherbourg, Queenstown, Southhampton."""

# Now we can make a quick factorplot to check out the results, note the x_order argument, used to deal with
sns.catplot(data=titanic_df, x='Embarked', hue='Pclass', kind='count', order=['C', 'Q', 'S'])

"""An interesting find here is that in Queenstown, almost all the passengers that boarded there were 3rd class. It would be intersting to look at the economics of that town in that time period for further investigation.

Now let's take a look at the 4th question:

4.) Who was alone and who was with family?
"""

# Let's start by adding a new column to define alone
# We'll add the parent/child column with the sibsp column

titanic_df['Alone'] = titanic_df.Parch + titanic_df.SibSp
titanic_df['Alone']

titanic_df.info()

"""Now we know that if the Alone column is anything but 0, then the passenger had family aboard and wasn't alone. So let's change the column now so that if the value is greater than 0, we know the passenger was with his/her family, otherwise they were alone."""

# Look for >0 or ==0 to set alone status

titanic_df['Alone'].loc[titanic_df['Alone'] >0 ] = 'With family'
titanic_df['Alone'].loc[titanic_df['Alone'] ==0] = 'Alone'

# Let's check to make sure it worked
titanic_df

# Now let's get a simple visualization!
sns.catplot(data=titanic_df, x='Alone', palette='Blues', kind='count')

Great work! Now that we've throughly analyzed the data let's go ahead and take a look at the most interesting (and open-ended) question: What factors helped someone survive the sinking?

# Let's start by creating a new column for legibility purposes through mapping (Lec 36)
titanic_df["Survivor"] = titanic_df.Survived.map({0: "no", 1: "yes"})

# Let's just get a quick overall view of survived vs died. 
sns.catplot(data=titanic_df, x='Survivor', palette='Set1', kind='count')

So quite a few more people died than those who survived. Let's see if the class of the passengers had an effect on their survival rate, since the movie Titanic popularized the notion that the 3rd class passengers did not do as well as their 1st and 2nd class counterparts.


